import os
import json
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

client = Anthropic()

def read_agent(filename):
    with open(f"agents/{filename}", "r") as f:
        return f.read()

def call_agent(agent_instructions, user_message, agent_name):
    print(f"\n{'='*60}")
    print(f"Agent: {agent_name} is working...")
    print(f"{'='*60}\n")
    
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=1000,
        system=agent_instructions,
        messages=[
            {"role": "user", "content": user_message}
        ]
    )
    
    result = response.content[0].text
    print(result)
    return result

def validate_output(output, required_sections, agent_name):
    missing = []
    for section in required_sections:
        if section.lower() not in output.lower():
            missing.append(section)
    
    if missing:
        print(f"\nWarning: {agent_name} output missing: {missing}")
        print("Proceeding with caution.\n")
        return False
    
    print(f"{agent_name} output validated.\n")
    return True

def save_formatted_report(content, problem):
    from datetime import datetime
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    safe_name = problem[:30].replace(" ", "_").replace("/", "").replace("\n", "")
    filename = f"brief_{safe_name}_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
    
    formatted = f"""---
title: AI Consulting Brief
generated: {timestamp}
pipeline: Consulting Agent Pipeline v3.0
mode: Dynamic Orchestration
---

{content}

---
*Generated by AI multi-agent consulting pipeline using 
the Anthropic Claude API with dynamic orchestration.*
*Generated: {timestamp}*
"""
    
    os.makedirs("outputs", exist_ok=True)
    with open(f"outputs/{filename}", "w") as f:
        f.write(formatted)
    
    print(f"\nReport saved to outputs/{filename}")
    return filename

def run_intake(business_problem):
    intake_agent = read_agent("intake_agent.md")
    
    intake_response = call_agent(
        agent_instructions=intake_agent,
        user_message=f"Evaluate this business problem: {business_problem}",
        agent_name="Intake Agent"
    )
    
    first_line = intake_response.strip().split('\n')[0].strip()
    
    if first_line == "READY":
        print("\nIntake Agent: Problem complete. Proceeding...\n")
        return business_problem
    
    elif first_line == "NEEDS_CLARIFICATION":
        print("\nIntake Agent needs more information.\n")
        questions = '\n'.join(intake_response.strip().split('\n')[1:])
        print(f"Please answer:\n{questions}\n")
        additional_context = input("Your answers: ")
        enriched_problem = f"""
Original problem: {business_problem}

Additional context: {additional_context}
"""
        print("\nThank you. Proceeding...\n")
        return enriched_problem
    
    else:
        return business_problem

def run_orchestrator(business_problem):
    """
    Orchestrator reads the problem and dynamically decides
    which agents to call and in what order.
    Returns a list of agent names to execute.
    """
    print(f"\n{'='*60}")
    print("Orchestrator: Planning agent deployment...")
    print(f"{'='*60}\n")
    
    orchestrator = read_agent("orchestrator.md")
    
    plan_response = call_agent(
        agent_instructions=orchestrator,
        user_message=f"Business problem: {business_problem}",
        agent_name="Orchestrator"
    )
    
    # Parse the JSON plan
    try:
        # Clean the response in case there's any extra text
        cleaned = plan_response.strip()
        
        # Find JSON object in the response
        start = cleaned.find('{')
        end = cleaned.rfind('}') + 1
        if start != -1 and end != 0:
            json_str = cleaned[start:end]
            plan = json.loads(json_str)
            agent_sequence = plan.get("agents", [])
            reasoning = plan.get("reasoning", "")
            
            print(f"\nOrchestrator plan: {agent_sequence}")
            print(f"Reasoning: {reasoning}\n")
            return agent_sequence
        else:
            raise ValueError("No JSON found in response")
            
    except Exception as e:
        print(f"\nOrchestrator parsing issue: {e}")
        print("Using default agent sequence.\n")
        return [
            "problem_analyst",
            "solution_architect", 
            "risk_reviewer",
            "executive_summarizer"
        ]

def run_agent_by_name(agent_name, enriched_problem, previous_outputs):
    """
    Loads and runs a specific agent by name.
    Passes the enriched problem and all previous outputs as context.
    Returns the agent's output.
    """
    
    # Validation requirements per agent
    validation_map = {
        "problem_analyst": ["core pain point", "stakeholders", 
                           "current state", "key questions"],
        "solution_architect": ["proposed solution", "how it works", 
                              "implementation", "business impact"],
        "risk_reviewer": ["strengths", "key risks", "gaps"],
        "financial_modeler": ["cost to implement", "financial benefits", 
                             "roi timeline"],
        "change_management": ["stakeholder", "adoption risks", 
                             "change enablement"],
        "executive_summarizer": ["situation", "opportunity", 
                                "recommendation"]
    }
    
    try:
        agent_instructions = read_agent(f"{agent_name}.md")
    except FileNotFoundError:
        print(f"Agent file {agent_name}.md not found — skipping")
        return None
    
    # Build the user message based on agent type
    if agent_name == "problem_analyst":
        user_message = f"Analyze this business problem: {enriched_problem}"
    
    elif agent_name == "executive_summarizer":
        user_message = f"""Here is the complete consulting brief to summarize:

{previous_outputs}

Produce a one-page executive summary."""
    
    else:
        user_message = f"""Original business problem: {enriched_problem}

Previous analysis and outputs:
{previous_outputs}

Now complete your specialized task based on all of the above."""
    
    # Call the agent
    display_name = agent_name.replace("_", " ").title()
    result = call_agent(
        agent_instructions=agent_instructions,
        user_message=user_message,
        agent_name=display_name
    )
    
    # Validate the output
    if agent_name in validation_map:
        validate_output(result, validation_map[agent_name], display_name)
    
    return result

def run_pipeline(business_problem):
    print("\n CONSULTING AGENT PIPELINE v3.0 — DYNAMIC ORCHESTRATION")
    print(f"\n Business Problem: {business_problem}\n")
    
    # STEP 1: Intake Agent
    enriched_problem = run_intake(business_problem)
    
    # STEP 2: Orchestrator decides which agents to deploy
    agent_sequence = run_orchestrator(enriched_problem)
    
    # STEP 3: Run each agent in the orchestrator's chosen order
    outputs = {}
    previous_outputs = f"BUSINESS PROBLEM:\n{enriched_problem}\n"
    
    for agent_name in agent_sequence:
        result = run_agent_by_name(agent_name, enriched_problem, previous_outputs)
        
        if result:
            outputs[agent_name] = result
            display_name = agent_name.replace("_", " ").upper()
            previous_outputs += f"\n\n{display_name}:\n{result}"
    
    # STEP 4: Assemble final brief
    final_brief = "# AI Consulting Brief\n\n"
    final_brief += f"**Business Problem:** {enriched_problem}\n\n---\n\n"
    
    # Put executive summary first if it exists
    if "executive_summarizer" in outputs:
        final_brief += "## Executive Summary\n\n"
        final_brief += outputs["executive_summarizer"] + "\n\n---\n\n"
    
    # Then all other agents in order
    section_titles = {
        "problem_analyst": "Problem Analysis",
        "solution_architect": "Proposed Solution", 
        "risk_reviewer": "Risk Review",
        "financial_modeler": "Financial Model",
        "change_management": "Change Management Plan"
    }
    
    for agent_name in agent_sequence:
        if agent_name != "executive_summarizer" and agent_name in outputs:
            title = section_titles.get(agent_name, 
                    agent_name.replace("_", " ").title())
            final_brief += f"## {title}\n\n"
            final_brief += outputs[agent_name] + "\n\n---\n\n"
    
    # Save formatted timestamped report
    save_formatted_report(final_brief, business_problem)
    
    print(f"\n{'='*60}")
    print("PIPELINE COMPLETE — Dynamic Orchestration v3.0")
    print(f"Agents deployed: {agent_sequence}")
    print(f"{'='*60}\n")
    
    return final_brief

if __name__ == "__main__":
    print("\n ACCENTURE CONSULTING AGENT PIPELINE v3.0")
    print("Dynamic Orchestration — Agents selected per problem")
    print("--------------------------------------------------")
    business_problem = input("Enter the client's business problem: ")
    run_pipeline(business_problem)